### ISSUE TITLE
Fischer projection for SMILE of glucose throws an error

### ISSUE THREAD

**Issue by stephanweissenberger** [vandan-revanur/pychemprojections#4]
Input: C(C1C(C(C(C(O1)O)O)O)O)O

`from pychemprojections.fischer.visualization import plot_fischer_projection

input_smiles_for_fischer = "C(C1C(C(C(C(O1)O)O)O)O)O"
plot_fischer_projection(input_smiles_for_fischer)`

error:
`Traceback (most recent call last):
  File "/pychemprojections/playground.py", line 4, in <module>
    plot_fischer_projection(input_smiles_for_fischer)
  File "/pychemprojections/pychemprojections/fischer/visualization.py", line 312, in plot_fischer_projection
    sorted_carbons_neighbours_info = remove_unnecessary_neighbours(
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/pychemprojections/fischer/multiplechiral.py", line 337, in remove_unnecessary_neighbours
    sorted_carbons_neighbours_info[0]["substituents"].pop(-1)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

The input `[H]OC([H])([H])C1([H])OC([H])(O[H])C([H])(O[H])C([H])(O[H])C1([H])O[H]` in `get_carbon_neighbours_info_multiple_chiral` returns an empty value resulting in the error.

**Comment by vandan-revanur** [comment]
Please see this [Note](https://github.com/vandan-revanur/pychemprojections#fischer-projection) section of Readme.

**Comment by vandan-revanur** [comment]
You are facing the issue because of two reasons.

1. Your SMILES does not explicitly state the chiral atoms.
2. You are using the closed chain form of SMILES instead of the open chain isomeric SMILES.

Pychemprojections does not support certain SMILES of compounds where cyclic rings are formed with any of chiral carbon atoms present in the main chain.
Therefore, if you would like to draw the Fischer projection of sugars, use the open chain form isomeric SMILES of the compound.

For example, to draw the Fischer projection of Glucose, use the open chain isomeric SMILES which is:

`C([C@H]([C@H]([C@@H]([C@H](C=O)O)O)O)O)O`

instead of the closed chain SMILES:

`C([C@@H]1[C@H]([C@@H]([C@H](C(O1)O)O)O)O)O`
